# Generated by Django 3.0.1 on 2019-12-29 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advance_paid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desciption', models.TextField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.CharField(max_length=80, verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], default=2)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(verbose_name='Mobile Number')),
                ('pan', models.CharField(max_length=15, verbose_name='PAN Number')),
                ('date_joined', models.DateField(default=datetime.date.today, verbose_name='date of joining')),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Department', to='payroll.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Payrolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_of_salary', models.CharField(choices=[('JAN', 'JANUARY'), ('FEB', 'FEBURARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEP', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], default='JAN', max_length=20, verbose_name='Month')),
                ('pay_freq', models.CharField(choices=[('twice', 'SEMI-MONTHLY'), ('once', 'MONTHLY')], default='once', max_length=10, verbose_name='Pay Frequency')),
                ('basic_salary', models.CharField(max_length=10, verbose_name='Salary/month')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Advance_paid')),
                ('deduction', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='payroll.Deductions')),
                ('staff_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Department')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Name', to='payroll.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='advance_paid',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Department'),
        ),
        migrations.AddField(
            model_name='advance_paid',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Staff'),
        ),
    ]
