# Generated by Django 3.0.1 on 2019-12-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20191229_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrolls',
            name='advance',
        ),
    ]
