# Generated by Django 3.0.1 on 2019-12-29 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_payrolls_advance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advance_paid',
            old_name='amount',
            new_name='advance_amount',
        ),
        migrations.AddField(
            model_name='payrolls',
            name='advance_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Advance_paid'),
        ),
    ]
