# Generated by Django 3.0.1 on 2019-12-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20191229_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance_paid',
            name='month',
            field=models.CharField(choices=[('select', 'SELECT MONTH'), ('JAN', 'JANUARY'), ('FEB', 'FEBURARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEP', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], default='select', max_length=18),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='month_of_salary',
            field=models.CharField(choices=[('select', 'SELECT MONTH'), ('JAN', 'JANUARY'), ('FEB', 'FEBURARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEP', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], default='select', max_length=20, verbose_name='Month'),
        ),
    ]
