# Generated by Django 3.0.1 on 2019-12-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20191229_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolls',
            name='net_salary',
            field=models.IntegerField(default=0, verbose_name='Net Salary'),
        ),
    ]
