# Generated by Django 3.0.1 on 2019-12-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrolls_net_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolls',
            name='basic_salary',
            field=models.IntegerField(max_length=10, verbose_name='Salary/month'),
        ),
    ]
