# Generated by Django 3.0.1 on 2019-12-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20191229_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolls',
            name='advance_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='basic_salary',
            field=models.IntegerField(verbose_name='Salary/month'),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='net_salary',
            field=models.IntegerField(verbose_name='Net Salary'),
        ),
    ]
