# Generated by Django 3.0.1 on 2019-12-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_payrolls_net_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrolls',
            name='net_salary',
        ),
    ]
