# Generated by Django 3.0.1 on 2019-12-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_remove_payrolls_net_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolls',
            name='net_salary',
            field=models.IntegerField(default=0, verbose_name='Net Salary'),
        ),
    ]
