# Generated by Django 3.0.1 on 2019-12-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_payrolls_net_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolls',
            name='net_salary',
            field=models.IntegerField(verbose_name='Net Salary'),
        ),
    ]
