# Generated by Django 3.0.1 on 2019-12-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_remove_payrolls_net_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advance_paid',
            name='department',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='department',
        ),
        migrations.RemoveField(
            model_name='payrolls',
            name='staff_dept',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='departmentID',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
