# Generated by Django 3.0.1 on 2019-12-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_auto_20191230_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolls',
            name='advance_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Advance_paid'),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[(0, 'INR'), (1, 'US DOLLAR')], default=0, max_length=20)),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='payrolls',
            name='salary_currency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Currency', to='payroll.Currency'),
        ),
    ]
