# Generated by Django 3.0.1 on 2019-12-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_auto_20191230_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolls',
            name='salary_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Currency', to='payroll.Currency'),
        ),
    ]
