# Generated by Django 3.0.1 on 2019-12-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_auto_20191230_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(choices=[('inr', 'INR'), ('dollar', 'US DOLLAR')], default='inr', max_length=20),
        ),
    ]
