# Generated by Django 3.0.1 on 2019-12-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_auto_20191230_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrolls',
            name='salary_currency',
        ),
    ]
