# Generated by Django 3.0.1 on 2019-12-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_remove_payrolls_salary_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='currency',
            new_name='salary_currency',
        ),
    ]
