# Generated by Django 3.0.1 on 2019-12-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_auto_20191230_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolls',
            name='advance_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
