# Generated by Django 3.0.1 on 2019-12-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_auto_20191230_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
