# Generated by Django 3.0.1 on 2019-12-30 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_delete_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_currency', models.CharField(choices=[('no', 'Not Selected'), ('inr', 'INR'), ('dollar', 'US DOLLAR')], default='no', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='payrolls',
            name='pay_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Currency', to='payroll.Currency'),
        ),
    ]
