# Generated by Django 3.0.1 on 2019-12-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_auto_20191230_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='salary_currency',
            field=models.CharField(max_length=20, verbose_name='Currency'),
        ),
    ]
