# Generated by Django 3.0.1 on 2019-12-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_auto_20191230_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolls',
            name='advance_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Advance_paid'),
        ),
    ]
