# Generated by Django 3.0.1 on 2019-12-30 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_auto_20191230_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance_paid',
            name='advance_amount',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='advance_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Advance_paid', to_field='advance_amount'),
        ),
    ]
