# Generated by Django 3.0.1 on 2019-12-31 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_auto_20191230_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advance_paid',
            old_name='employee',
            new_name='name',
        ),
    ]
