# Generated by Django 3.0.1 on 2019-12-31 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_auto_20191231_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductions',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='advance_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Advance_paid', to_field='advance_amount'),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='deduction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Deductions'),
        ),
    ]
