# Generated by Django 3.0.1 on 2019-12-31 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_auto_20191231_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance_paid',
            name='advance_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='advance_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Advance_paid'),
        ),
    ]
